# -*- coding: utf-8 -*-
"""simpleChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VW3iAo8H_d8G2MBZOJKZSjXtDeATyF4
"""

!pip install streamlit

!pip install pyngrok

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

# import google.generativeai as genai
# #import os

# #genai.configure(api_key=os.environ["API_KEY"])
# Google_api_key = ""
# model = genai.GenerativeModel('gemini-1.5-flash')
! streamlit run app.py & npx localtunnel --port 8501

! streamlit run app.py & npx localtunnel --port 8501

!apt-get install git

!git config --global user.name "Noorasghar09"
!git config --global user.email "noorasghar2004@gmail.com"

!git clone https://github.com/Noorasghar09/SimpleChatbot.git

!cp /content/app.py /content/SimpleChatbot/

# Commented out IPython magic to ensure Python compatibility.
# %cd SimpleChatbot